module.exports = function(sequelize, DataTypes) {
  return sequelize.define('SPRMVI', {
   modfor:  { type: DataTypes.STRING, fields:['SPRMVI_MODFOR'], primaryKey: true},
   codfor:  { type: DataTypes.STRING, fieldss:['SPRMVI_CODFOR'], primaryKey: true},
   nrofor:  { type: DataTypes.INTEGER, fields:['SPRMVI_NROFOR'], primaryKey: true},
   nroasg:  { type: DataTypes.INTEGER, fields:['SPRMVI_NROASG'], primaryKey: true},
   nroitm:  { type: DataTypes.INTEGER, fields:['SPRMVI_NROITM'], primaryKey: true},
   fchmov:  { type: DataTypes.DATE, fields:['SPRMVI_FCHMOV']},
   tipcla:  { type: DataTypes.STRING, fields:['SPRMVI_TIPCLA']},
   codsub:  { type: DataTypes.STRING, fields:['SPRMVI_CODSUB']},
   tipdes:  { type: DataTypes.STRING, fields:['SPRMVI_TIPDES']},
   estact:  { type: DataTypes.STRING, fields:['SPRMVI_ESTACT']},
   tiphas:  { type: DataTypes.STRING, fields:['SPRMVI_TIPHAS']},
   estnew:  { type: DataTypes.STRING, fields:['SPRMVI_ESTNEW']},
   clasif:  { type: DataTypes.STRING, fields:['SPRMVI_CLASIF']},
   fchreq:  { type: DataTypes.DATE, fields:['SPRMVI_FCHREQ']},
   fchlim:  { type: DataTypes.DATE, fields:['SPRMVI_FCHLIM']},
   rubro1:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR01']},
   rubro2:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR02']},
   rubro3:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR03']},
   rubro4:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR04']},
   rubro5:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR05']},
   rubro6:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR06']},
   rubro7:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR07']},
   rubro8:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR08']},
   rubro9:  { type: DataTypes.STRING, fields:['SPRMVI_RUBR09']},
   rubro10: { type: DataTypes.STRING, fields:['SPRMVI_RUBR10']},
   observ:  { type: DataTypes.STRING, fields:['SPRMVI_OBSERV']},
   modrel:  { type: DataTypes.STRING, fields:['SPRMVI_MODREL']},
   codrel:  { type: DataTypes.STRING, fields:['SPRMVI_CODREL']},
   nrorel:  { type: DataTypes.INTEGER, fields:['SPRMVI_NROREL']},
   asgrel:  { type: DataTypes.INTEGER, fields:['SPRMVI_ASGREL']},
   motivo:  { type: DataTypes.STRING, fields:['SPRMVI_MOTIVO']},
   aplare:  { type: DataTypes.STRING, fields:['SPRMVI_APLARE']},
   aplcod:  { type: DataTypes.STRING, fields:['SPRMVI_APLCOD']},
   pedare:  { type: DataTypes.STRING, fields:['SPRMVI_PEDARE']},
   asgare:  { type: DataTypes.STRING, fields:['SPRMVI_ASGARE']},
   nroint:  { type: DataTypes.INTEGER, fields:['SPRMVI_NROINT']},
   usernt:  { type: DataTypes.STRING, fields:['SPRMVI_USERNT']},
   oriare:  { type: DataTypes.STRING, fields:['SPRMVI_ORIARE']},
   orires:  { type: DataTypes.STRING, fields:['SPRMVI_ORIRES']},
   hornov:  { type: DataTypes.STRING, fields:['SPRMVI_HORNOV']},
   minuto:  { type: DataTypes.STRING, fields:['SPRMVI_MINUTO']},
   codtem:  { type: DataTypes.STRING, fields:['SPRMVI_CODTEM']},
   codpri:  { type: DataTypes.STRING, fields:['SPRMVI_CODPRI']},
   obscli:  { type: DataTypes.STRING, fields:['SPRMVI_OBSCLI']},
   desfun:  { type: DataTypes.TEXT, fields:['SPRMVI_DESFUN']},
   ordenx:  { type: DataTypes.INTEGER, fields:['SPRMVI_ORDENX']},
   tipasg:  { type: DataTypes.STRING, fields:['SPRMVI_TIPASG']},
   tippro:  { type: DataTypes.INTEGER, fields:['USR_SPRMVI_TIPPRO']},
   tipapl:  { type: DataTypes.INTEGER, fields:['USR_SPRMVI_TIPAPL']},
   ocurre:  { type: DataTypes.INTEGER, fields:['USR_SPRMVI_OCURRE']},
   tippro:  { type: DataTypes.STRING, fields:['USR_SPRMVI_CALIFI']},
   tipapl:  { type: DataTypes.STRING.BINARY, fields:['USR_SPRMVI_MAINOT']},
   ocurre:  { type: DataTypes.INTEGER, fields:['USR_SPRMVI_TIPGSL']},
   tippro:  { type: DataTypes.INTEGER, fields:['USR_SPRMVI_PRIGSL']},
   tipapl:  { type: DataTypes.INTEGER, fields:['USR_SPRMVI_CALGSL']},
   ocurre:  { type: DataTypes.TEXT, fields:['USR_SPRMVI_ACARAI']},
   fecalt:  { type: DataTypes.DATE, fields:['SPRMVI_FECALT']},
   fecmod:  { type: DataTypes.DATE, fields:['SPRMVI_FECMOD']},
   userid:  { type: DataTypes.STRING, fields:['SPRMVI_USERID']},
   ultopr:  { type: DataTypes.STRING.BINARY, fields:['SPRMVI_ULTOPR']},
   debaja:  { type: DataTypes.STRING.BINARY, fields:['SPRMVI_DEBAJA']},
   hormov:  { type: DataTypes.STRING, fields:['SPRMVI_HORMOV']},
   module:  { type: DataTypes.STRING, fields:['SPRMVI_MODULE']},
   oalias:  { type: DataTypes.STRING, fields:['SPRMVI_OALIAS']},
   lottra:  { type: DataTypes.STRING, fields:['SPRMVI_LOTTRA']},
   lotrec:  { type: DataTypes.STRING, fields:['SPRMVI_LOTREC']},
   lotori:  { type: DataTypes.STRING, fields:['SPRMVI_LOTORI']},
   sysver:  { type: DataTypes.STRING, fields:['SPRMVI_SYSVER']},
   cmpver:  { type: DataTypes.STRING, fields:['SPRMVI_CMPVER']},
   msgpre:  { type: DataTypes.STRING, fields:['VIRT_MSGPRE']},
   nobscli: { type: DataTypes.STRING, fields:['NEW_SPRMVI_OBSCLI']},
   noberv:  { type: DataTypes.STRING, fields:['NEW_SPRMVI_OBSERV']}
 }, {
   getterMethods   : {
      // activos      : function() =>{ return this.firstname + ' ' + this.lastname }
   },
   setterMethods   : {
     // fullName: (value) => {
     //     var names = value.split(' ');
     //     this.setDataValue('firstname', names.slice(0, -1).join(' '));
     //     this.setDataValue('lastname', names.slice(-1).join(' '));
     },
   }
});
