module.exports = function(sequelize, DataTypes) {
  return sequelize.define('SPRMVH', {
    modfor:  { type: DataTypes.STRING, fields:['SPRMVH_MODFOR'], primaryKey: true},
    codfor:  { type: DataTypes.STRING, fields:['SPRMVH_CODFOR'], primaryKey: true},
    nrofor:  { type: DataTypes.INTEGER, fields:['SPRMVH_NROFOR'], primaryKey: true},
    fchmov:  { type: DataTypes.DATE, fields:['SPRMVH_FCHMOV']},
    tipcla:  { type: DataTypes.STRING, fields:['SPRMVH_TIPCLA']},
    codsub:  { type: DataTypes.STRING, fields:['SPRMVH_CODSUB']},
    tipdes:  { type: DataTypes.STRING, fields:['SPRMVH_TIPDES']},
    estact:  { type: DataTypes.STRING, fields:['SPRMVH_ESTACT']},
    tiphas:  { type: DataTypes.STRING, fields:['SPRMVH_TIPHAS']},
    estnew:  { type: DataTypes.STRING, fields:['SPRMVH_ESTNEW']},
    clasif:  { type: DataTypes.STRING, fields:['SPRMVH_CLASIF']},
    descrp:  { type: DataTypes.TEXT, fields:['SPRMVH_DESCRP']},
    nrocta:  { type: DataTypes.STRING, fields:['SPRMVH_NROCTA']},
    fchreq:  { type: DataTypes.DATE, fields:['SPRMVH_FCHREQ']},
    fchlim:  { type: DataTypes.DATE, fields:['SPRMVH_FCHLIM']},
    nroint:  { type: DataTypes.INTEGER, fields:['SPRMVH_NROINT']},
    rubro1:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR01']},
    rubro2:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR02']},
    rubro3:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR03']},
    rubro4:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR04']},
    rubro5:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR05']},
    rubro6:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR06']},
    rubro7:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR07']},
    rubro8:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR08']},
    rubro9:  { type: DataTypes.STRING, fields:['SPRMVH_RUBR09']},
    rubro10: { type: DataTypes.STRING, fields:['SPRMVH_RUBR10']},
    aplare:  { type: DataTypes.STRING, fields:['SPRMVH_APLARE']},
    aplcod:  { type: DataTypes.STRING, fields:['SPRMVH_APLCOD']},
    pedare:  { type: DataTypes.STRING, fields:['SPRMVH_PEDARE']},
    pedres:  { type: DataTypes.STRING, fields:['SPRMVH_PEDRES']},
    aplare:  { type: DataTypes.STRING, fields:['SPRMVI_APLARE']},
    usernt:  { type: DataTypes.INTEGER, fields:['SPRMVH_USERNT']},
    refere:  { type: DataTypes.STRING, fields:['SPRMVH_REFERE']},
    dircor:  { type: DataTypes.TEXT, fields:['SPRMVH_DIRCOR']},
    codtem:  { type: DataTypes.STRING, fields:['SPRMVH_CODTEM']},
    codpri:  { type: DataTypes.STRING, fields:['SPRMVH_CODPRI']},
    dircor:  { type: DataTypes.TEXT, fields:['SPRMVH_OLEOLE']},
    tarrel:  { type: DataTypes.STRING.BINARY, fields:['SPRMVH_TARREL']},
    codtar:  { type: DataTypes.STRING, fields:['SPRMVH_CODTAR']},
    porcen:  { type: DataTypes.DECIMAL, fields:['SPRMVH_PORCEN']},
    desfun:  { type: DataTypes.TEXT, fields:['SPRMVH_DESFUN']},
    observ:  { type: DataTypes.TEXT, fields:['SPRMVH_OBSERV']},
    nroitm:  { type: DataTypes.INTEGER, fields:['SPRMVH_NROITM']},
    ordenx:  { type: DataTypes.INTEGER, fields:['SPRMVH_ORDENX']},
    tipasg:  { type: DataTypes.STRING, fields:['SPRMVH_TIPASG']},
    hornov:  { type: DataTypes.STRING, fields:['SPRMVH_HORNOV']},
    oripro:  { type: DataTypes.STRING, fields:['SPRMVH_ORIPRO']},
    ucorort:  { type: DataTypes.STRING.BINARY, fields:['USR_SPRMVH_CORORT']},
    uusaobj:  { type: DataTypes.STRING, fields:['USR_SPRMVH_USAOBJ']},
    utipcla:  { type: DataTypes.STRING, fields:['USR_SPRMVH_TIPCLA']},
    ucodtra:  { type: DataTypes.STRING, fields:['USR_SPRMVH_CODATR']},
    uvalatr:  { type: DataTypes.STRING, fields:['USR_SPRMVH_VALATR']},
    utippro:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_TIPPRO']},
    utipapl:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_TIPAPL']},
    uocurre:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_OCURRE']},
    ucalifi:  { type: DataTypes.STRING, fields:['USR_SPRMVH_CALIFI']},
    uclient:  { type: DataTypes.STRING, fields:['USR_SPRMVH_CLIENT']},
    uitm:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_ITM']},
    ucanal:  { type: DataTypes.STRING, fields:['USR_SPRMVH_CANAL']},
    uvalord:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_VALORD']},
    utipgsl:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_TIPGSL']},
    uprigsl:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_PRIGSL']},
    ucalgsl:  { type: DataTypes.INTEGER, fields:['USR_SPRMVH_CALGSL']},
    uuancar:  { type: DataTypes.STRING, fields:['USR_SPRMVH_UANCAR']},
    uancara:  { type: DataTypes.TEXT, fields:['USR_SPRMVH_ANCARA']},
    uctapro:  { type: DataTypes.STRING, fields:['USR_SPRMVH_CTAPRO']},
    ucodpro:  { type: DataTypes.STRING, fields:['USR_SPRMVH_CODPRO']},
    uolepro:  { type: DataTypes.STRING, fields:['USR_SPRMVH_OLEPRO']},
    nrosub:  { type: DataTypes.STRING, fields:['SPRMVH_NROSUB']},
    modori:  { type: DataTypes.STRING, fields:['SPRMVH_MODORI']},
    codori:  { type: DataTypes.STRING, fields:['SPRMVH_CODORI']},
    nroori:  { type: DataTypes.INTEGER, fields:['SPRMVH_NROORI']},
    modori:  { type: DataTypes.STRING, fields:['SPRMVH_MODORI']},
    manfch:  { type: DataTypes.STRING, fields:['SPRMVH_MANFCH']},
    canasg:  { type: DataTypes.INTEGER, fields:['SPRMVH_CANASG']},
    ctrlin:  { type: DataTypes.STRING, fields:['SPRMVH_CTRLIN']},
    ctacon:  { type: DataTypes.STRING, fields:['SPRMVH_CTACON']},
    contac:  { type: DataTypes.STRING, fields:['SPRMVH_CONTAC']},
    codemp:  { type: DataTypes.STRING, fields:['SPRMVH_CODEMP']},
    empori:  { type: DataTypes.STRING, fields:['SPRMVH_EMPORI']},
    newcto:  { type: DataTypes.STRING, fields:['SPRMVH_NEWCTO']},
    riesgo:  { type: DataTypes.STRING, fields:['SPRMVH_RIESGO']},
    fchdes:  { type: DataTypes.DATE, fields:['SPRMVH_FCHDES']},
    mailcp:  { type: DataTypes.STRING, fields:['SPRMVH_MAILCP']},
    fecalt:  { type: DataTypes.DATE, fields:['SPRMVH_FECALT']},
    fecmod:  { type: DataTypes.DATE, fields:['SPRMVH_FECMOD']},
    userid:  { type: DataTypes.STRING, fields:['SPRMVH_USERID']},
    ultopr:  { type: DataTypes.STRING.BINARY, fields:['SPRMVH_ULTOPR']},
    debaja:  { type: DataTypes.STRING.BINARY, fields:['SPRMVH_DEBAJA']},
    hormov:  { type: DataTypes.STRING, fields:['SPRMVH_HORMOV']},
    module:  { type: DataTypes.STRING, fields:['SPRMVH_MODULE']},
    oalias:  { type: DataTypes.STRING, fields:['SPRMVH_OALIAS']},
    lottra:  { type: DataTypes.STRING, fields:['SPRMVH_LOTTRA']},
    lotrec:  { type: DataTypes.STRING, fields:['SPRMVH_LOTREC']},
    lotori:  { type: DataTypes.STRING, fields:['SPRMVH_LOTORI']},
    sysver:  { type: DataTypes.STRING, fields:['SPRMVH_SYSVER']},
    cmpver:  { type: DataTypes.STRING, fields:['SPRMVH_CMPVER']}

}, {
  getterMethods   : {
     // activos      : function() =>{ return this.firstname + ' ' + this.lastname }
  },
  setterMethods   : {
    // fullName: (value) => {
    //     var names = value.split(' ');
    //     this.setDataValue('firstname', names.slice(0, -1).join(' '));
    //     this.setDataValue('lastname', names.slice(-1).join(' '));
    },
  }
});
